<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Astro.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Novolis.Astro.Abstractions/Novolis.Astro.Abstractions.csproj" />
    <ProjectReference Include="../../src/Novolis.Astro.Catalog/Novolis.Astro.Catalog.csproj" />
    <ProjectReference Include="../../src/Novolis.Astro.Routing/Novolis.Astro.Routing.csproj" />
    <ProjectReference Include="../../src/Novolis.Astro.Assessment/Novolis.Astro.Assessment.csproj" />
    <ProjectReference Include="../../src/Novolis.Astro.Overlay/Novolis.Astro.Overlay.csproj" />
    <ProjectReference Include="../../src/Novolis.Astro.Plotting/Novolis.Astro.Plotting.csproj" />
  </ItemGroup>
</Project>
