// Pregenerates Catalog.Data *.g.cs packs from novolis-astro/data/*.json.
// Run from novolis-astro repo root:
//   dotnet run -c Release --file tools/pregen-catalog.cs

#:property PublishAot=false
#:property PackAsTool=false
#:property Nullable=enable
#:property ImplicitUsings=enable
#:property TargetFramework=net10.0

using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

var root = FindRepoRoot(Environment.CurrentDirectory);
var dataDir = Path.Combine(root, "data");
var outDir = Path.Combine(root, "src", "Novolis.Astro.Catalog.Data", "Generated");
Directory.CreateDirectory(outDir);

const double LyPerPc = 3.261563777;

var nearSolPath = Path.Combine(dataDir, "nearsol-100.json");
var hygPath = Path.Combine(dataDir, "hyg-local.json");
if (!File.Exists(nearSolPath) || !File.Exists(hygPath))
{
    Console.Error.WriteLine("Missing data/nearsol-100.json or data/hyg-local.json");
    return 1;
}

var jsonOpts = new JsonSerializerOptions { PropertyNameCaseInsensitive = true };

var nearSol = JsonSerializer.Deserialize<List<NearSolEntry>>(File.ReadAllText(nearSolPath), jsonOpts) ?? [];
var nearSystems = nearSol
    .Select(e => new GenSystem(
        e.Id,
        e.Name,
        e.X,
        e.Y,
        e.Z,
        ParseSpectralClass(e.Spectral),
        e.Spectral,
        null,
        null,
        null,
        e.Tags ?? []))
    .OrderBy(s => Dist(s))
    .ThenBy(s => s.Id, StringComparer.Ordinal)
    .ToList();

WritePack(Path.Combine(outDir, "NearSol100.g.cs"), "NearSol100", nearSystems, "Johnston near-Sol (ly); vendored from nearsol-100.json");

var hyg = JsonSerializer.Deserialize<List<HygEntry>>(File.ReadAllText(hygPath), jsonOpts) ?? [];
var hygSystems = hyg
    .Where(e => e.X is not null && e.Y is not null && e.Z is not null)
    .Select(e =>
    {
        var xLy = (double)e.X!.Value * LyPerPc;
        var yLy = (double)e.Y!.Value * LyPerPc;
        var zLy = (double)e.Z!.Value * LyPerPc;
        var name = DisplayName(e);
        double? lum = e.Lum is > 0 ? (double)e.Lum.Value : null;
        double? absMag = e.Absmag is not null ? (double)e.Absmag.Value : null;
        return new GenSystem(
            e.Id.ToString(CultureInfo.InvariantCulture),
            name,
            xLy,
            yLy,
            zLy,
            ParseSpectralClass(e.Spect),
            e.Spect,
            lum,
            absMag,
            null,
            []);
    })
    .OrderBy(s => Dist(s))
    .ThenBy(s => int.TryParse(s.Id, out var n) ? n : int.MaxValue)
    .ThenBy(s => s.Id, StringComparer.Ordinal)
    .ToList();

WritePack(Path.Combine(outDir, "HygLocal1901.g.cs"), "HygLocal1901", hygSystems, "HYG-style local slice; XYZ converted pc→ly from hyg-local.json");

Console.WriteLine($"Wrote NearSol100 ({nearSystems.Count}) and HygLocal1901 ({hygSystems.Count}) to {outDir}");
return 0;

static string FindRepoRoot(string start)
{
    var dir = new DirectoryInfo(start);
    while (dir is not null)
    {
        if (File.Exists(Path.Combine(dir.FullName, "Novolis.Astro.slnx")) ||
            Directory.Exists(Path.Combine(dir.FullName, "data")) && Directory.Exists(Path.Combine(dir.FullName, "src")))
            return dir.FullName;
        dir = dir.Parent;
    }

    return start;
}

static double Dist(GenSystem s) => Math.Sqrt(s.X * s.X + s.Y * s.Y + s.Z * s.Z);

static string DisplayName(HygEntry e)
{
    if (!string.IsNullOrWhiteSpace(e.Proper)) return e.Proper!;
    if (!string.IsNullOrWhiteSpace(e.Bf)) return e.Bf!;
    if (!string.IsNullOrWhiteSpace(e.Gl)) return e.Gl!;
    if (!string.IsNullOrWhiteSpace(e.Hd)) return "HD " + e.Hd;
    if (!string.IsNullOrWhiteSpace(e.Hip)) return "HIP " + e.Hip;
    return e.Id.ToString(CultureInfo.InvariantCulture);
}

static string ParseSpectralClass(string? spect)
{
    if (string.IsNullOrWhiteSpace(spect)) return "Unknown";
    var text = spect.Trim().ToUpperInvariant();
    if (text.Contains("WD", StringComparison.Ordinal) || text.StartsWith('D'))
        return "WD";
    return text[0] switch
    {
        'O' => "O",
        'B' => "B",
        'A' => "A",
        'F' => "F",
        'G' => "G",
        'K' => "K",
        'M' => "M",
        'L' => "L",
        'T' => "T",
        'Y' => "Y",
        _ => "Unknown"
    };
}

static void WritePack(string path, string propertyName, IReadOnlyList<GenSystem> systems, string comment)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine($"// {comment}");
    sb.AppendLine("// Re-run: dotnet run -c Release --file tools/pregen-catalog.cs");
    sb.AppendLine("#nullable enable");
    sb.AppendLine("using Novolis.Astro.Abstractions;");
    sb.AppendLine("using Novolis.Astro.Catalog;");
    sb.AppendLine();
    sb.AppendLine("namespace Novolis.Astro.Catalog.Data;");
    sb.AppendLine();
    sb.AppendLine("public static partial class CatalogPacks");
    sb.AppendLine("{");
    sb.AppendLine($"    /// <summary>{comment}</summary>");
    sb.AppendLine($"    public static IReadOnlyList<StarSystem> {propertyName} {{ get; }} = Create{propertyName}();");
    sb.AppendLine();
    sb.AppendLine($"    static StarSystem[] Create{propertyName}()");
    sb.AppendLine("    {");
    sb.AppendLine("        return");
    sb.AppendLine("        [");
    foreach (var s in systems)
    {
        sb.Append("            new StarSystem(");
        sb.Append(Lit(s.Id));
        sb.Append(", ");
        sb.Append(Lit(s.Name));
        sb.Append(", new StarCoords(");
        sb.Append(F(s.X));
        sb.Append(", ");
        sb.Append(F(s.Y));
        sb.Append(", ");
        sb.Append(F(s.Z));
        sb.Append("), SpectralClass.");
        sb.Append(s.SpectralClass);
        sb.Append(", ");
        sb.Append(TagsLit(s.Tags));
        sb.Append(", luminositySolar: ");
        sb.Append(NullableF(s.LuminositySolar));
        sb.Append(", effectiveTemperatureK: ");
        sb.Append(NullableF(s.EffectiveTemperatureK));
        sb.Append(", spectralDesignation: ");
        sb.Append(s.SpectralDesignation is null ? "null" : Lit(s.SpectralDesignation));
        sb.Append(", absoluteMagnitude: ");
        sb.Append(NullableF(s.AbsoluteMagnitude));
        sb.AppendLine("),");
    }

    sb.AppendLine("        ];");
    sb.AppendLine("    }");
    sb.AppendLine("}");
    File.WriteAllText(path, sb.ToString());
}

static string Lit(string s) =>
    "\"" + s.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

static string F(double v) => v.ToString("G17", CultureInfo.InvariantCulture);

static string NullableF(double? v) => v is null ? "null" : F(v.Value);

static string TagsLit(IReadOnlyList<string> tags)
{
    if (tags.Count == 0) return "null";
    return "[" + string.Join(", ", tags.Select(Lit)) + "]";
}

sealed record GenSystem(
    string Id,
    string Name,
    double X,
    double Y,
    double Z,
    string SpectralClass,
    string? SpectralDesignation,
    double? LuminositySolar,
    double? AbsoluteMagnitude,
    double? EffectiveTemperatureK,
    IReadOnlyList<string> Tags);

sealed class NearSolEntry
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public double X { get; set; }
    public double Y { get; set; }
    public double Z { get; set; }
    public string? Spectral { get; set; }
    public List<string>? Tags { get; set; }
}

sealed class HygEntry
{
    public int Id { get; set; }
    public string? Hip { get; set; }
    public string? Hd { get; set; }
    public string? Gl { get; set; }
    public string? Bf { get; set; }
    public string? Proper { get; set; }
    public string? Spect { get; set; }
    public decimal? X { get; set; }
    public decimal? Y { get; set; }
    public decimal? Z { get; set; }
    public decimal? Lum { get; set; }
    public decimal? Absmag { get; set; }
}
